# Generated by Django 2.1 on 2018-10-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_rotation', '0004_bakingslot_baker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakingslot',
            name='img',
        ),
    ]
