# Generated by Django 2.0.6 on 2018-08-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baking_rotation', '0002_auto_20180703_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakingslot',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='bakingslot',
            name='img',
            field=models.ImageField(default='/tmp/uploads/2018/09/01', upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
