# Generated by Django 2.0.6 on 2018-09-18 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baking_rotation', '0003_auto_20180807_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakingslot',
            name='baker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
