# Generated by Django 2.1 on 2018-11-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baking_rotation', '0005_remove_bakingslot_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakingslot',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/baking_slot_images/%Y/%m/%d/'),
        ),
    ]
