# Generated by Django 2.1 on 2019-10-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baking_rotation', '0006_bakingslot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakingslot',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
    ]
